name: flutter_chargebee_js_example
description: Demonstrates how to use the flutter_chargebee_js plugin. Based on the official braze_plugin example.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_chargebee_js:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
