name: flutter_chargebee_js
description: Unofficial ChargbeeJS Plugin for Flutter for Web. It is mostly a Flutter Web Plugin acting as a wrapper around the official Chargebee JS Web SDK.
repository: https://github.com/radvansky-tomas/flutter_chargebee_js
version: 0.0.2

environment:
  sdk: ">=2.17.6 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # JavaScript Interop
  js: ^0.6.7

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterChargebeeJSWebPlugin
        fileName: src/flutter_chargebee_js_web.dart
